export const CollegeData = [
    { id: 1, name: 'Gael Schuh', course: 'English Composition', age: 22 },
    { id: 2, name: 'Brynne Bance', course: 'World History', age: 26 },
    { id: 3, name: 'Opaline Benzing', course: 'Introduction to Sociology', age: 27 },
    { id: 4, name: 'Bonny Decayette', course: 'Chemistry 101', age: 20 },
    { id: 5, name: 'Kaylyn Bertolaccini', course: 'English Composition', age: 25 },
    { id: 6, name: 'Wylie Jowle', course: 'Calculus I', age: 26 },
    { id: 7, name: 'Timmie Emson', course: 'Environmental Science', age: 25 },
    { id: 8, name: 'Madelon Daniely', course: 'Calculus I', age: 26 },
    { id: 9, name: 'Dougy Andreone', course: 'Chemistry 101', age: 21 },
    { id: 10, name: 'Aliza Edscer', course: 'Art Appreciation', age: 24 },
    { id: 11, name: 'Kriste Lawlie', course: 'Introduction to Business', age: 21 },
    { id: 12, name: 'Maritsa Franzelini', course: 'Introduction to Sociology', age: 21 },
    { id: 13, name: 'Aprilette Brewett', course: 'Introduction to Psychology', age: 22 },
    { id: 14, name: 'Antonella McDougall', course: 'Introduction to Psychology', age: 22 },
    { id: 15, name: 'Ruperta Baudoux', course: 'World History', age: 22 },
    { id: 16, name: 'Nahum Feighney', course: 'Introduction to Sociology', age: 18 },
    { id: 17, name: 'Phelia Liepina', course: 'Introduction to Sociology', age: 25 },
    { id: 18, name: 'Onida Cheltnam', course: 'World History', age: 25 },
    { id: 19, name: 'Ignace Emmert', course: 'Chemistry 101', age: 18 },
    { id: 20, name: 'Tony Boobyer', course: 'English Composition', age: 19 }
  ];
